#!/usr/bin/env node
/**
 * Generates `src/app/shared/components/icon-registry.ts` by fetching SVGs
 * from Google Material Symbols Rounded (24px, fill variant).
 *
 * Usage:
 *   node scripts/generate-icons.mjs            # fetch all icons
 *   node scripts/generate-icons.mjs add close  # fetch specific icons only
 *
 * The icon list is derived from every `name="..."` and `name="..."` binding
 * across the app's HTML and TS files. Run this after adding a new icon
 * reference to regenerate the registry.
 *
 * Icons are fetched from:
 *   https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded/{name}/default/24px.svg
 *
 * The script caches results so re-runs are fast and offline-friendly.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const OUTPUT = join(ROOT, 'src/app/shared/components/icon-registry.ts');
const CACHE_DIR = join(ROOT, 'scripts/.icon-cache');

const BASE_URL =
  'https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded';

/**
 * Every icon name used in the app. To find them:
 *   grep -rohP "name=[\"'][a-z_]+[\"']" src/app/ | sed "s/.*['\"]//;s/['\"]//"
 *   grep -rohP "return '[a-z_]+'" src/app/ | sed "s/.*'//;s/'//"
 *
 * Add new icons here when you reference them in templates or TS.
 */
const ICON_NAMES = [
  'add',
  'arrow_back',
  'auto_awesome',
  'calculate',
  'check',
  'check_circle',
  'chevron_left',
  'chevron_right',
  'close',
  'cloud',
  'cloud_done',
  'cloud_off',
  'cloud_upload',
  'content_copy',
  'delete',
  'delete_sweep',
  'description',
  'download',
  'edit',
  'error',
  'expand_more',
  'group',
  'grid_view',
  'help',
  'image',
  'info',
  'inventory_2',
  'layers',
  'logout',
  'menu',
  'person',
  'progress_activity',
  'receipt_long',
  'remove',
  'restart_alt',
  'save',
  'science',
  'search',
  'sell',
  'settings',
  'shopping_cart',
  'star',
  'star_outline',
  'sync',
  'table_chart',
  'tag',
  'text_snippet',
  'upload',
  'warning',
];

async function fetchIcon(name) {
  const cachePath = join(CACHE_DIR, `${name}.svg`);

  if (existsSync(cachePath)) {
    return readFileSync(cachePath, 'utf-8');
  }

  const url = `${BASE_URL}/${name}/default/24px.svg`;
  console.log(`  fetching ${name}...`);

  try {
    const res = await fetch(url);
    if (!res.ok) {
      throw new Error(`HTTP ${res.status}`);
    }
    let svg = await res.text();

    // Normalize: ensure fill="currentColor" so the icon inherits text color.
    if (!svg.includes('fill="currentColor"')) {
      svg = svg.replace(/<svg /, '<svg fill="currentColor" ');
    }

    if (!existsSync(CACHE_DIR)) {
      mkdirSync(CACHE_DIR, { recursive: true });
    }
    writeFileSync(cachePath, svg);
    return svg;
  } catch (err) {
    console.error(`  ✗ ${name}: ${err.message}`);
    process.exit(1);
  }
}

async function main() {
  const requested = process.argv.slice(2);
  const names = requested.length > 0 ? requested : ICON_NAMES;

  console.log(`Generating icon registry with ${names.length} icons...\n`);

  const entries = [];
  for (const name of names) {
    const svg = await fetchIcon(name);
    // Escape backticks in SVG (shouldn't be any, but just in case).
    const escaped = svg.replace(/`/g, '\\`');
    entries.push(`  '${name}': \`${escaped}\`,`);
  }

  const content = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Source: Google Material Symbols Rounded (24px, fill variant)
// To add an icon: add its name to ICON_NAMES in the script and re-run.

export const ICON_PATHS: Record<string, string> = {
${entries.join('\n')}
};
`;

  writeFileSync(OUTPUT, content);
  console.log(`\n✓ Wrote ${OUTPUT} (${names.length} icons)`);
}

main();
